### ISSUE TITLE
Headers hierarchy is not honored

### ISSUE THREAD

**Issue by nnlkcncff** [toxoxi/remnote-table-of-contents#4]
Look at this structure in Markdown:
```Markdown
# 1
## 1.1
## 1.2

# 2
## 2.1
## 2.2
```

In RemNote headers syntax should be something like this:
```RemNote
/h1 1
/h2 1.1
/h2 1.2
/h1 2
/h2 2.1
/h2 2.2
```

That should be displayed as something like this:

 - 1
	 - 1.1
	 - 1.2
 - 2
	 - 2.1
	 - 2.2

But instead they are displayed without any indentation like this:

 - 1
 - 1.1
 - 1.2
 - 2
 - 2.1
 - 2.2

**Comment by toxoxi** [comment]
@nnlkcncff 
Thank you for your reporting. The behavior is expected as I designed.
https://github.com/toxoxi/remnote-table-of-contents?tab=readme-ov-file#more-details

I think the hierarchy displayed in the sidebar should be determined by the hierarchy of the rems, which is based on indent size, because the top level rem (= h1) should be parent of the content.

**Comment by nnlkcncff** [comment]
@toxoxi, got it. But it would be great to add at least a switch that could enable this logic. Personally, I miss this feature. If you use only Rem indentation, the text does not look very nice due to the floating left edge.

But anyway thanks for your work, it's a great plugin anyway.
